### ISSUE TITLE
DockLib < 10.14 using show_recents errors out with AttributeError

### ISSUE THREAD

**Issue by WardsParadox** [homebysix/docklib#15]
Docklib when used to set attributes for preferences not available to the OS errors out with AttributeError. If you are setting this attribute, make sure you have a test for the OS it exists on.
Example:
```python
import docklib
import platform
from distutils.version import LooseVersion

dock = docklib.Dock()

if LooseVersion(platform.mac_ver()[0]) >= LooseVersion("10.14"):
    dock.show_recents = True;
dock.
dock.save()
```

**Comment by homebysix** [comment]
This might be fixed now. Could you try on the 1.0.3 branch? Here's some code that will simply toggle show_recents:

```
#!/usr/bin/python
from docklib import Dock
dock = Dock()
dock.show_recents = not dock.show_recents
dock.save()
```

**Comment by homebysix** [comment]
Closing due to no response.
