### ISSUE TITLE
Recently used not updated

### ISSUE THREAD

**Issue by jberkner** [homebysix/docklib#17]
Using docklib 1.0.3 branch with show_recents fix. MacOS 10.14.5

When adding items to the dock, if the item already exists in recently used, it will remain in recently used (therefore appearing twice) after calling dock.save().

Expected result is the recently used would be updated/refreshed with dock.save()

Workaround: from terminal calling `killall 'Dock'` to update/refresh the recently used

**Comment by homebysix** [comment]
This and #18 should be fixed by c916ead. Could I have you test it out?

**Comment by homebysix** [comment]
Closing due to no response.
