### ISSUE TITLE
Issue with disabling show-recents

### ISSUE THREAD

**Issue by JonB5366** [homebysix/docklib#18]
`dock.show_recents = True; `   works as expected however when trying with False or 0, it does not disable the show recents.

I have tried the defaults write (full path to dock plist) show-recents -float 0
Then I did killall Dock command and it works which suggest the python script might be not passing the False (or 0) correctly.

**Comment by homebysix** [comment]
show-recents should be a Boolean, not a float. However, your point stands: I can confirm that `defaults write com.apple.dock show-recents -bool false; killall Dock` works but docklib's `dock.show_recents = False; dock.save()` does not.

**Comment by JonB5366** [comment]
Tested the updated commit and it is now working. Thank you very much!
