### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by 71vl17** [homebysix/docklib#27]
Hello. 

Can't use any of examples, for example, "Add App to the right side of the Dock" shows this:
<img width="569" alt="Импортированный снимок экрана 2020-05-29 в 14 38 48" src="https://user-images.githubusercontent.com/56300682/83256057-67760c00-a1ba-11ea-8072-a09b9e3510db.png">

What I'm doing wrong?

**Comment by 71vl17** [comment]
Also, I'd like to add a folder (with some apps) to dock, but not in the right part (where Downloads and trashbin are). Is it possible with docklib? Or maybe you can suggest some other tweaks for this? Thank you

**Comment by homebysix** [comment]
Hi @71vl17 - could you try again with the latest version of docklib?

Also, just verify that the `persistent-apps` list is not actually empty?

**Comment by homebysix** [comment]
Closing due to no response.
