### ISSUE TITLE
domain error when executed as root with sudo -u

### ISSUE THREAD

**Issue by TomBoehm** [homebysix/docklib#5]
when executed eg. via Munki (running as root)
```
sudo -u $loggedInUser python - <<EOF
from docklib import Dock
dock = Dock()
dock.orientation = 'left'
EOF
```
the command `subprocess.call(['/bin/launchctl',....` fails with "Could not find domain for"

**Comment by WardsParadox** [comment]
Might be the way you're calling it. The launchctl commands are expecting to run as a user. Calling it via sudo -u might still trip up the subprocess and run it as root. Would highly suggest looking at running it via JAMF or via outset (could even rig up an OnDemand type script for outset)

**Comment by homebysix** [comment]
@WardsParadox is correct. `docklib` expects to be run in user context (where there is a com.apple.dock preference domain), not root context.
